language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/SLE-12-GA/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2-core-dev yast2 yast2-network" -g "rspec:2.14.1 yast-rake gettext rubocop:0.28.0"
script:
    - rake check:syntax
    - rake check:pot
    - rubocop
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check

